apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: joshuatallman/webserver
        resources:
        envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: phonebook-cm
        ports:
        - containerPort: 80

        # env:
        #   - name: MYSQL_DATABASE_HOST
        #     value: mysql-service
        #   - name: MYSQL_DATABASE
        #     value: phonebook
        #   - name: MYSQL_USER
        #     value: clarus
        #   - name: MYSQL_PASSWORD
        #     value: Pl123456
